[package]
name = "media-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmm = { path = "../libmm" }
thiserror = "1.0"
directories = "4.0"